#!/bin/bash

rm -f repack_zip/boot/zImage

mv arch/arm64/boot/Image.gz-dtb repack_zip/boot/zImage
find -name "*.ko" -exec mv {} repack_zip/system/lib/modules \;

cd repack_zip

DATE=`date +%d-%m-%Y`;
zip -r ../../release_santoni/Clarity-Santoni-$DATE.zip *

